server:
  port: 8021
  servlet:
      context-path: /forex-bot

spring:
#  html乱码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  #项目名
  application:
    name: forex-bot
  #配置rabbitMq 服务器
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
  datasource:
    # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间：默认10min
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 自动提交
      auto-commit: true
      # 连接存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 3000
      # 测试连接是否可用
      connection-test-query: SELECT 1

  redis:
    # 服务器地址
    host: 139.159.188.75
    # 端口号
    port: 6379
    # 密码
    password: 089916
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞时间
        max-wait: 10000ms
        # 最大最小空闲连接
        max-idle: 200
        min-idle: 5